// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnlhyrcjockhwtrjnpgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubGh5cmNqb2NraHd0cmpucGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MTM4MDMsImV4cCI6MjA1NjM4OTgwM30.ZTATa439TOlSHBeq6UH5WZ-I23ueuECnBH_Er2Y9iio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);